# Permalinks
permalink:           pretty

# Setup
title:               The Sin of Man
tagline:             by Noah Bradley
url:                 https://noahbradley.github.io/
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Noah Bradley
  url:               https://noahbradley.com
  email:             noah@noahbradley.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/poole/poole

pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'

# Gems
gems:
  - jekyll-gist
